# This file was generated by GoReleaser. DO NOT EDIT.
cask "jsm" do
  name "jsm"
  desc "JSON Schema Manager (jsm) - Registry-first tool for managing and validating JSON schemas."
  homepage "https://github.com/andyballingall/json-schema-manager"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jsm"

  on_macos do
    on_intel do
      url "https://github.com/andyballingall/json-schema-manager/releases/download/v#{version}/jsm_darwin_amd64.tar.gz"
      sha256 "7dbca07bc713b3e02dfdd87ce959b964e7efbe1933df9e6a35fcdd85cbc633e1"
    end
    on_arm do
      url "https://github.com/andyballingall/json-schema-manager/releases/download/v#{version}/jsm_darwin_arm64.tar.gz"
      sha256 "941d54aeb065d92480188df870efe8ce51c5f1d7ef37cea399d50d7ce8a4718c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andyballingall/json-schema-manager/releases/download/v#{version}/jsm_linux_amd64.tar.gz"
      sha256 "3e30fe83fa15209a0168ee90ebfe959e9a5b070839b7e6377240226d52d06336"
    end
    on_arm do
      url "https://github.com/andyballingall/json-schema-manager/releases/download/v#{version}/jsm_linux_arm64.tar.gz"
      sha256 "6a186c406e47d4ee6e360d1c95149991e32a6b10eed978fe0800a2baeb0b9b54"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jsm"]
    end
  end

  # No zap stanza required
end
