# This file was generated by GoReleaser. DO NOT EDIT.
cask "jsm" do
  name "jsm"
  desc "JSON Schema Manager (jsm) - Registry-first tool for managing and validating JSON schemas."
  homepage "https://github.com/andyballingall/json-schema-manager"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jsm"

  on_macos do
    on_intel do
      url "https://github.com/andyballingall/json-schema-manager/releases/download/v#{version}/jsm_darwin_amd64.tar.gz"
      sha256 "e6966a476852316dd5ca73763732b18822354ce82d54cf34dd2f1e43eaa3f2e0"
    end
    on_arm do
      url "https://github.com/andyballingall/json-schema-manager/releases/download/v#{version}/jsm_darwin_arm64.tar.gz"
      sha256 "6085f737f48dadd659bf35cf69a7aa34f6896c4dd20d5145ad85d052064433f7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andyballingall/json-schema-manager/releases/download/v#{version}/jsm_linux_amd64.tar.gz"
      sha256 "6623f1f5f45442884a084343b5b6795ce5fa5c6d408cde2419d3656e7593d8df"
    end
    on_arm do
      url "https://github.com/andyballingall/json-schema-manager/releases/download/v#{version}/jsm_linux_arm64.tar.gz"
      sha256 "8201c8fbd6408f0fa8b590b14f743252d047afe221e52b2264ec174f78db4108"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jsm"]
    end
  end

  # No zap stanza required
end
