# This file was generated by GoReleaser. DO NOT EDIT.
cask "jsm" do
  name "jsm"
  desc "JSON Schema Manager (jsm) - Registry-first tool for managing and validating JSON schemas."
  homepage "https://github.com/andyballingall/json-schema-manager"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jsm"

  on_macos do
    on_intel do
      url "https://github.com/andyballingall/json-schema-manager/releases/download/v#{version}/jsm_darwin_amd64.tar.gz"
      sha256 "65de8acb26b2b34a80522522daa3753ed80ed8992130625bfd382a2f73e1a572"
    end
    on_arm do
      url "https://github.com/andyballingall/json-schema-manager/releases/download/v#{version}/jsm_darwin_arm64.tar.gz"
      sha256 "b722576a35aa4eee374746444fdc7a55de1db9164009090bb5ebeb8b722a9658"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andyballingall/json-schema-manager/releases/download/v#{version}/jsm_linux_amd64.tar.gz"
      sha256 "3356f2fc6fcdec8cca981e4d8a1db0b3b0f07f6ba5494795d79eefa8fe6f0451"
    end
    on_arm do
      url "https://github.com/andyballingall/json-schema-manager/releases/download/v#{version}/jsm_linux_arm64.tar.gz"
      sha256 "7dc03307828a250f6865f88f416a4351519180567e9c24733e4274459400298a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jsm"]
    end
  end

  # No zap stanza required
end
